#!/usr/bin/env python3
"""Regenerate docs/FAULT_LIBRARY.md from the fault definitions in code.

The library is written once, in ``kavach_diag/faults.py``. This script renders
it to Markdown so the documentation cannot drift from what the engine actually
classifies. Run it after adding or editing a fault:

    python3 tools/generate_fault_library.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from kavach_diag import faults  # noqa: E402

OUTPUT = ROOT / "docs" / "FAULT_LIBRARY.md"

PREAMBLE = """<!-- Generated by tools/generate_fault_library.py - do not edit by hand. -->

# Kavach fault library

Every condition the diagnostic engine can classify, with the evidence that
produces it, the engineering action it points to, and where the failure goes
next.

Codes are stable: quote them in the S&T failure register entry and in the
divisional Kavach performance return so that the same condition is counted the
same way across sections and months.

Severities are defaults. A few rules raise or lower the severity from the
evidence - a marginal signal above the working limit is reported below a signal
that has fallen through it, and authentication failures on an already degraded
radio link are reported as probable corruption rather than as forged messages.

The responsibility and escalation columns are working defaults and are meant to
be edited to match the division's own JPO / SOP for Kavach.

"""


def render() -> str:
    parts = [PREAMBLE]

    parts.append("## Index\n")
    parts.append("| Code | Severity | Subsystem | Condition |")
    parts.append("| --- | --- | --- | --- |")
    for definition in sorted(faults.FAULTS.values(), key=lambda d: d.code):
        parts.append(
            f"| `{definition.code}` | {definition.severity} | "
            f"{definition.subsystem} | {definition.title} |"
        )
    parts.append("")

    for subsystem, definitions in sorted(faults.by_subsystem().items()):
        parts.append(f"\n## {subsystem}\n")
        for definition in definitions:
            parts.append(f"### `{definition.code}` - {definition.title}\n")
            parts.append(f"**Severity:** {definition.severity}\n")
            parts.append(f"**Signature:** {definition.signature}\n")
            parts.append(f"**Likely cause:** {definition.likely_cause}\n")
            parts.append(f"**Action:** {definition.action}\n")
            parts.append(f"**Responsibility:** {definition.responsibility}\n")
            parts.append(f"**Escalation:** {definition.escalation}\n")
            if definition.references:
                parts.append(f"**References:** {'; '.join(definition.references)}\n")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Written: {OUTPUT.relative_to(ROOT)} ({len(faults.FAULTS)} definitions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
